### DISCUSSION TITLE
隐藏块引用[[产生的面包屑 CSS to hide breadcrumbs

### DISCUSSION THREAD

**Discussion by ghost** [5eagull/RemNote-Chinese-chat-group#26] [CSS主题分享]
CSS to hide breadcrumbs
```css
/* 隐藏面包屑 */
.rem-reference.button.rem-reference-link .gray {    
    display : none; 
}
.rem-reference.button.rem-reference-link .join-arrow {    
    display : none; 
}
.rem-indented-indicator {    
    display:none;
}

```
