### DISCUSSION TITLE
左上角标志隐藏 The logo in the upper left corner is hidden

### DISCUSSION THREAD

**Discussion by ghost** [5eagull/RemNote-Chinese-chat-group#6] [CSS主题分享]
下边三小组是一个CSS可以 左上角log隐藏
```CSS
/*左上角log隐藏*/
#document-sidebar_top #logo img {     height: 0;     margin: 10px 0 7px; }

/*取消log的多余空间*/
#document-sidebar_top #logo {     font-size: 0em;     font-weight: 700;     text-align: center;     margin-bottom: 2px;     color: rgba(25,25,25,.8)!important; }

/*左上角库标志变灰*/
#document-sidebar__account-capsule #document-sidebar__account-capsule__text{ 	background-color: #c9c9c9; }

```
